spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/linlichuan/datadic.git
#          username:
#          password:
          search-paths: /config/**
      label: master
  config:
    name: configCenter
server:
  port: 8888