spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/linlichuan/datadic.git
          username: 807977007@qq.com
          password: githubllc007
          search-paths: /config/**
      label: master
  config:
    name: configCenter
server:
  port: 8888