server:
  port: 8101
  servlet:
    context-path: /api
eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://192.168.10.253:8761/eureka/
    enabled: false
spring:
  application:
    name: api-service_local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    #是否开启驼峰转换
    map-underscore-to-camel-case: true
    #是否在null时也调用setter显示
    call-setters-on-nulls: true
    cache-enabled: true