package com.llc.springcloud.zhservice.dao.mapper.all;

import com.llc.springcloud.zhservice.entity.Story;

public interface StoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table story
     *
     * @mbggenerated Thu Dec 10 18:26:56 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table story
     *
     * @mbggenerated Thu Dec 10 18:26:56 CST 2020
     */
    int insert(Story record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table story
     *
     * @mbggenerated Thu Dec 10 18:26:56 CST 2020
     */
    int insertSelective(Story record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table story
     *
     * @mbggenerated Thu Dec 10 18:26:56 CST 2020
     */
    Story selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table story
     *
     * @mbggenerated Thu Dec 10 18:26:56 CST 2020
     */
    int updateByPrimaryKeySelective(Story record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table story
     *
     * @mbggenerated Thu Dec 10 18:26:56 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Story record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table story
     *
     * @mbggenerated Thu Dec 10 18:26:56 CST 2020
     */
    int updateByPrimaryKey(Story record);
}