package com.llc.springcloud.zhservice.dao.mapper.all;

import com.llc.springcloud.zhservice.entity.TopRecord;

public interface TopRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_record
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_record
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    int insert(TopRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_record
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    int insertSelective(TopRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_record
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    TopRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_record
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    int updateByPrimaryKeySelective(TopRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_record
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    int updateByPrimaryKey(TopRecord record);
}