package com.llc.springcloud.bean.zhapi.entity;

import java.io.Serializable;

public class StoryDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story_detail.id
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story_detail.image_hue
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    private String imageHue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story_detail.image_source
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    private String imageSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story_detail.title
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story_detail.url
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story_detail.image
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story_detail.share_url
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    private String shareUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story_detail.detail_id
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    private Integer detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story_detail.type
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story_detail.is_top_story
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    private Boolean isTopStory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story_detail.body
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table story_detail
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story_detail.id
     *
     * @return the value of story_detail.id
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story_detail.id
     *
     * @param id the value for story_detail.id
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story_detail.image_hue
     *
     * @return the value of story_detail.image_hue
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public String getImageHue() {
        return imageHue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story_detail.image_hue
     *
     * @param imageHue the value for story_detail.image_hue
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public void setImageHue(String imageHue) {
        this.imageHue = imageHue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story_detail.image_source
     *
     * @return the value of story_detail.image_source
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public String getImageSource() {
        return imageSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story_detail.image_source
     *
     * @param imageSource the value for story_detail.image_source
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public void setImageSource(String imageSource) {
        this.imageSource = imageSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story_detail.title
     *
     * @return the value of story_detail.title
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story_detail.title
     *
     * @param title the value for story_detail.title
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story_detail.url
     *
     * @return the value of story_detail.url
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story_detail.url
     *
     * @param url the value for story_detail.url
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story_detail.image
     *
     * @return the value of story_detail.image
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story_detail.image
     *
     * @param image the value for story_detail.image
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story_detail.share_url
     *
     * @return the value of story_detail.share_url
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public String getShareUrl() {
        return shareUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story_detail.share_url
     *
     * @param shareUrl the value for story_detail.share_url
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public void setShareUrl(String shareUrl) {
        this.shareUrl = shareUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story_detail.detail_id
     *
     * @return the value of story_detail.detail_id
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public Integer getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story_detail.detail_id
     *
     * @param detailId the value for story_detail.detail_id
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story_detail.type
     *
     * @return the value of story_detail.type
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story_detail.type
     *
     * @param type the value for story_detail.type
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story_detail.is_top_story
     *
     * @return the value of story_detail.is_top_story
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public Boolean getIsTopStory() {
        return isTopStory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story_detail.is_top_story
     *
     * @param isTopStory the value for story_detail.is_top_story
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public void setIsTopStory(Boolean isTopStory) {
        this.isTopStory = isTopStory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story_detail.body
     *
     * @return the value of story_detail.body
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story_detail.body
     *
     * @param body the value for story_detail.body
     *
     * @mbggenerated Thu Dec 10 18:27:32 CST 2020
     */
    public void setBody(String body) {
        this.body = body;
    }
}