package com.llc.springcloud.bean.zhapi.entity;

import java.io.Serializable;
import java.util.Date;

public class TopRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column top_record.id
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column top_record.date
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column top_record.top_date
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    private Date topDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column top_record.story_ids
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    private String storyIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table top_record
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column top_record.id
     *
     * @return the value of top_record.id
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column top_record.id
     *
     * @param id the value for top_record.id
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column top_record.date
     *
     * @return the value of top_record.date
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column top_record.date
     *
     * @param date the value for top_record.date
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column top_record.top_date
     *
     * @return the value of top_record.top_date
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    public Date getTopDate() {
        return topDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column top_record.top_date
     *
     * @param topDate the value for top_record.top_date
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    public void setTopDate(Date topDate) {
        this.topDate = topDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column top_record.story_ids
     *
     * @return the value of top_record.story_ids
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    public String getStoryIds() {
        return storyIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column top_record.story_ids
     *
     * @param storyIds the value for top_record.story_ids
     *
     * @mbggenerated Fri Dec 11 11:03:55 CST 2020
     */
    public void setStoryIds(String storyIds) {
        this.storyIds = storyIds;
    }
}