server:
  port: 8102
  servlet:
    context-path: /cpt
    encoding:
      charset: UTF-8
      enabled: true
      force-request: true
      force-response: true
eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
spring:
  application:
    name: cpt
